#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Keyword {
    Fn,
    Let,
    Const,
    Struct,

    If,
    Else,
    While,
    Do,
    For,
    Break,
    Continue,
    Return,

    Spawn,
    Chan,

    True,
    False,
    Null,

    As,
    Sizeof,
    New,

    Interface,
    Impl,
    Import,
    Pub,
    Enum,
    Match,
    Defer,
    Mut,
    Type,
    Move,
}

impl Keyword {
    pub fn to_lexeme(&self) -> &'static str {
        match self {
            Keyword::Fn       => "fn",
            Keyword::Let      => "let",
            Keyword::Const    => "const",
            Keyword::Struct   => "struct",
            Keyword::If       => "if",
            Keyword::Else     => "else",
            Keyword::While    => "while",
            Keyword::Do       => "do",
            Keyword::For      => "for",
            Keyword::Break    => "break",
            Keyword::Continue => "continue",
            Keyword::Return   => "return",
            Keyword::Spawn    => "spawn",
            Keyword::Chan     => "chan",
            Keyword::True     => "true",
            Keyword::False    => "false",
            Keyword::Null     => "null",
            Keyword::As       => "as",
            Keyword::Sizeof   => "sizeof",
            Keyword::New      => "new",
            Keyword::Interface => "interface",
            Keyword::Impl      => "impl",
            Keyword::Import    => "import",
            Keyword::Pub       => "pub",
            Keyword::Enum      => "enum",
            Keyword::Match     => "match",
            Keyword::Defer     => "defer",
            Keyword::Mut       => "mut",
            Keyword::Type      => "type",
            Keyword::Move      => "move",
        }
    }

    pub fn from_str(value: &str) -> Option<Keyword> {
        match value {
            "fn"       => Some(Keyword::Fn),
            "let"      => Some(Keyword::Let),
            "const"    => Some(Keyword::Const),
            "struct"   => Some(Keyword::Struct),
            "if"       => Some(Keyword::If),
            "else"     => Some(Keyword::Else),
            "while"    => Some(Keyword::While),
            "do"       => Some(Keyword::Do),
            "for"      => Some(Keyword::For),
            "break"    => Some(Keyword::Break),
            "continue" => Some(Keyword::Continue),
            "return"   => Some(Keyword::Return),
            "spawn"    => Some(Keyword::Spawn),
            "chan"     => Some(Keyword::Chan),
            "true"     => Some(Keyword::True),
            "false"    => Some(Keyword::False),
            "null"     => Some(Keyword::Null),
            "as"       => Some(Keyword::As),
            "sizeof"   => Some(Keyword::Sizeof),
            "new"      => Some(Keyword::New),
            "interface" => Some(Keyword::Interface),
            "impl"      => Some(Keyword::Impl),
            "import"    => Some(Keyword::Import),
            "pub"       => Some(Keyword::Pub),
            "enum"      => Some(Keyword::Enum),
            "match"     => Some(Keyword::Match),
            "defer"     => Some(Keyword::Defer),
            "mut"       => Some(Keyword::Mut),
            "type"      => Some(Keyword::Type),
            "move"      => Some(Keyword::Move),
            _ => None,
        }
    }
}
